# Generated by Django 4.2.7 on 2023-11-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=15)),
                ('timezone', models.CharField(max_length=10)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
